config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do 
  	member do
  		get :following, :followers
  	end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  get 'tweetslist', to: 'pages#tweets'

  resources :tweets do
  	resources :replies
  	resources :likes

  end

  resources :users do
    resources :notifications, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :followings,       only: [:create, :destroy]

end

app/models/reply.rb
class Reply < ApplicationRecord

	belongs_to :tweet
	belongs_to :user


end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @tweet = Tweet.find(params[:tweet_id])
    user = Tweet.find(params[:tweet_id]).user_id
    usernamee = User.find(user).email 
    @username, *rest = usernamee.split(/@/) 

    @reply = @tweet.replies.new

    # function for like by whoever using tooltip 
    like = Like.where(tweet_id:@tweet.id)
    if like.count == 0
      @usernn = 'Like!'
    else
      @usernn = 'Liked by '
      like.each do |likeuser|
        username = User.find(likeuser.user_id).email
        usern, *rest = username.split(/@/)
        if @usernn == 'Liked by '
          @usernn += usern
        else
          @usernn += ', ' + usern
        end
      end
    end
    # end of like by whoever function 

    @noti = Notification.where(tweet: @user)

    # For all replies show
    @allreplies = @tweet.replies.all
    # end of all reply show
    
  end

  def create
    reply_params = params[:reply].permit(:body)
    tweet = Tweet.find(params[:tweet_id])
    @reply = tweet.replies.new(reply_params)
    @reply.user_id = current_user.id
    @reply.save

    word = @reply.body.split(/\W+/)
    words = word[0] 

    userreply = @reply.user_id
    username, *rest = User.find(userreply).email.split(/@/)
    user = current_user

    message = username + ' replied to your tweet, ' + words + '...'
    tweetuser = Tweet.find(params[:tweet_id]).user_id
    notify = user.notifications.create(notify: message, tweet: tweetuser )

    redirect_back(fallback_location: root_path)
    # # respond_to do |f|
    # #   f.html { new_tweet_reply_path(tweet_id: tweet.id) }
    # #   f.js {render :new}
    # end

  end

  def destroy
    reply = Reply.find_by(tweet_id: params[:tweet_id], id: params[:id])
    reply.destroy
    redirect_back(fallback_location: root_path)

  end
	
end

app/views/replies/new.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3" style="margin-top: 80px;">
      <div class="box">
          <div class="boxwrap">
            <div class="row">
              <div class="col-md-1"><div class="profilepic img-circle"><i class="glyphicon glyphicon-camera"></i></div></div>
              <div class="col-md-11">
                <small>@<%= @username %>
                <span class="tweettime">&bull; <%= time_ago_in_words(@tweet.created_at) %> ago </span></small>
                <div><%= @tweet.body %></div>
                <div class="row tooltip-tweet" style="margin-top: 20px;">
                  <div class="col-md-2">
                    
                    <!-- 
                    check if the user has liked a tweet 
                    -->
                    <% likecheck = @tweet.likes.find_by(user_id: current_user.id) %>
                    <% likeall = Like.where(tweet_id:@tweet.id) %>
                    <% if likecheck != nil %>
                      <% like = @tweet.id %>
                      <%= link_to tweet_like_path(tweet_id: @tweet.id, id: likecheck.id), method: :delete do %>
                        <button style="color: #1DA1F2;" data-toggle="tooltip" data-placement="top" title="<%= @usernn %>!">
                          <span class="glyphicon glyphicon-heart"></span><small> <%= likeall.count %></small>
                        </button>
                      <% end %>
                    <% elsif likecheck == nil %>
                      <%= link_to tweet_likes_path(tweet_id: @tweet.id),method: :post do %>
                      <button style="color: #434A54;" data-toggle="tooltip" data-placement="top" title="<%= @usernn %>!">
                        <span class="glyphicon glyphicon-heart"></span><small> <%= likeall.count %></small>
                      </button>
                      <% end %>
                    <% end %>
                    <!-- 
                    end of check if user liked a tweet 
                    -->

                  </div>

                  <!--
                   reply function 
                  -->
                  <div class="col-md-2">
                    
                    <button style="color: #434A54;">
                      <span class="glyphicon glyphicon-comment" data-toggle="tooltip" data-placement="top" title="Reply"></span><small> <%= if @tweet.replies.count != 0 then @tweet.replies.count end %></small>
                    </button>


                  </div>
                  <!--
                   end of reply function 
                  -->

                </div>
              </div>
            </div>
            <hr>

            <!--
             All Replies
             -->
             <% @allreplies.each do |reply| %>
              <% user = User.find(reply.user_id).email %>
              <% username, *rest = user.split(/@/) %>
                <% if reply.user_id == current_user.id %>

                  <small>
                    <%= link_to tweet_reply_path(tweet_id: reply.tweet_id, id: reply.id), method: :delete do %>
                    <span class="glyphicon glyphicon-trash" style="margin-left: 10px;"></span>
                    <% end %>
                  </small>

                <% end %>
                
                
                  <small id="replyuser">@<%= username %> says: </small>
                  <p id="replybody"><%= reply.body %></p>
                  <hr>
             <div id="replies"></div>   
             <% end %>
             
             <!--
              End All relies 
             -->
            
            <!-- new reply -->
            <%= form_for @reply, url: tweet_replies_path(tweet_id: @tweet.id), method: :post do |f| %>
            <textarea class="form-control" name="reply[body]" rows="3"></textarea>
            <button class="pull-right btn btn-primary" name="commit" style="margin-top: 10px; margin-left: 3px;">Reply</button>
            <% end %>
            <%= link_to root_path do %>
            <button class="pull-right btn btn-default" style="margin-top: 10px;">Back</button>
            <% end %>

          </div>

            
          

        </div>




    </div>
  
</div>
<hr>
</div>

app/views/replies/new.js.erb
$('#replies').append('<%= render 'layouts/reply' %>')