config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do 
  	member do
  		get :following, :followers
  	end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  get 'tweetslist', to: 'pages#tweets'

  resources :tweets do
  	resources :replies
  	resources :likes

  end

  resources :users do
    resources :notifications, only: [:create, :destroy]
    member do
      get :following, :followers
    end
  end

  resources :followings,       only: [:create, :destroy]

end

app/views/pages/index.html.erb
<!-- <div class="cover"> -->
  <div class="carousel slide carousel-fade" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
        </div>
        <div class="item">
        </div>
        <div class="item">
        </div>
        <div class="item">
        </div>
        <div class="item">
        </div>
        <div class="item">
        </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-1">
        <div class="desc">
          <h2>Welcome to AC Tweet!</h2>
          <h3>Connect with your Alpha Camp peers!</h3>
        </div>
      </div>
      <div class="col-md-4">
        <!-- login box -->
        <div class="introbox">
          <%= form_for(:user, url: session_path(:user)) do |f| %>
            <input type="email" name="user[email]" id="user_email" class="form-control" placeholder="Email"> 
            <div class="row" style="margin-top: 5px; margin-bottom: 5px;">
              <div class="col-md-8"><input type="password" name="user[password]" id="user_password" class="form-control" placeholder="Password"></div>
              <div class="col-md-4"><%= f.submit 'Sign in', class: 'btn btn-default' %></div>
            </div>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me, class: 'control-label' %>
            <%= link_to "Forgot password?", new_password_path(:user) %>
          <% end %>
        </div>
        <!-- end login box -->
        <div class="introbox" style="margin-top: 10px;">
          <h4>New to AC-Tweet? <span style="color: grey;">Sign up</span></h4>
          <%= form_for(:user, url: registration_path(:user)) do |f| %>
              

            <div class="field">
              <input type="email" id="user_email" name="user[email]" class="form-control" placeholder="Email">
            </div>

            <div class="field">
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %>
              <input type="password" name="user[password]" id="user_password" class="form-control" placeholder="Password" style="margin-top: 5px; margin-bottom: 5px;">
            </div>

            <div class="field">
              <input type="password" name="user[password_confirmation]" id="user_password_confirmation" class="form-control" placeholder="Confirm Password" style="margin-bottom: 5px;">
            </div>

            <div class="actions">
              <%= f.submit "Sign up for AC-Tweet", class: 'btn btn-primary pull-right' %>
            </div><br><br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<!-- </div> -->
<%= render 'layouts/footer' %>

app/views/pages/tweets.html.erb
<div class="tweets">
  <div class="container">
    <div class="row">
      <!-- 
        User Profile Box (left) 
      -->
      <div class="col-md-3">
        <div class="box">
          <div>
<!--             <span><i class="glyphicon glyphicon-camera"></i></span> -->
            <!-- <%= image_tag current_user.image, :size => "120x100", :class => "profile-image" %> -->
            <% if current_user.image.url != nil %>
            <center><%= image_tag current_user.image.url, :class=> "img-circular" %></center>
            <% end %>
          </div>
          <div class="username">
            <h4><%= @username %></h4>
          </div>
          <div class="status">
            <div class="row">
              <div class="col-md-4">
                <div class="statushead">Tweets</div>
                <div class="statsnum"><%= @tweets.count %></div>
              </div>
              <div class="col-md-4">
                <div class="statushead">Following</div>
                <div class="statsnum" id="statscreate"><%= @userfollow.following.count %></div>
              </div>
              <div class="col-md-4">
                <div class="statushead">Followers</div>
                <div class="statsnum"><%= @userfollow.followers.count %></div>
              </div>
            </div>
          </div>
        </div>
        <div class="box" id="whotofollow">
          <table class="table table-hover tablecont">
            <thead>
              <th><h5>Who to follow</h5></th>
            </thead>
            <tbody>
              <% @alluser.each do |user| %>
              <% if current_user != user %>
              <% email = user.email %>
              <% useremail, *rest = email.split(/@/) %>
              <tr id="follow-<%= user.id %>">
                <%= render 'layouts/follow', {user: user, useremail: useremail } %>
              </tr>
              <% end %>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>

      <!-- 
        Tweets Box (Center)
      -->
      <div class="col-md-6">
        <div class="tweetshead">
          <h4>All User Tweets</h4>
           &bull;
           <%= link_to root_path do %>
          <a href="">
            <small> Refresh</small>
            <i class="glyphicon glyphicon-refresh"></i>
          </a>
          <% end %>
        </div>
        <!--
         check for any tweets 
        -->
        <% if Tweet.count - Tweet.where(user_id: current_user.id).count == 0 %>
          <i>There are no tweets.</i>
        
        <% else %>

        <!--
         call each tweet 
        -->
        <div id="tweetupdate">
        <%= render 'layouts/tweet', userstweets: @userstweets %>

      </div>
      <% end %>
    </div>
      <!--
       end of  call each tweet  
      -->
      <!-- 
        new tweet box (right)
      -->
      <div class="col-md-3">
        <div class="boxwrap usertweet">
          <%= form_for @tweet, url: tweets_path, method: :post do |f| %>
            <textarea row="2" name="tweet[body]" id="tweet_body" class="form-control" placeholder="New Tweet" required></textarea>
            <button type="submit" name="commit" class="btn btn-primary" data-type="last">Tweet</button>
            <!-- <%= f.submit "Tweet", class: 'btn btn-primary pull-righ' %> -->
          <% end %>
        </div>
        <div class="box boxwrap usertweets">
          <h4>Your tweets</h4>
          <% if @usertweets.count == 0 %>
            <i><small>You have no tweets.</small></i>
          <% end %>
          <ul class="list-group">
            <% @usertweets.each do |tweet| %>
              <li class="list-group-item">
                <%= link_to tweet_path(id:tweet.id), method: :delete do %>
                <button class="trash">
                  <span class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="top" title="Delete tweet!"></span>
                </button>
                <% end %>
                <span class="badge badge-default glyphicon glyphicon-comment">
                    <%= tweet.replies.count %>
                </span><span class="badge badge-default glyphicon glyphicon-heart">
                    <%= tweet.likes.count %>
                </span>
                <%= link_to new_tweet_reply_path(tweet_id: tweet.id) do %>
                <%= tweet.body %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>